### ISSUE TITLE
How to disable only the console nag?  Or, set alert_log_file to what?

### ISSUE THREAD

**Issue by bronson** [skylightio/skylight-ruby#15]
Hi, every time I launch a Rails console, I see:

```
W, [2014-10-08T13:22:00.945517 #61832]  WARN -- : [SKYLIGHT] [0.3.21] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message, set `alert_log_file` in your config.)
```

Set it to what?  Setting `config/application.rb` doesn't seem to work:
```
    config.skylight.alert_log_file = false
    config.skylight.alert_log_file = Rails.root.join('tmp', 'garbage')
```

Setting `config/skylight.yml` kind of works HOWEVER it disables all warnings, not just the rails console nag.
```
alert_log_file: "tmp/garbage"
```

I definitely would like to continue to receive these warnings:

```
       W, [2014-10-08T20:15:25.032247 #1022]  WARN -- : [SKYLIGHT] [0.3.21] You are running in the build environment but haven't added it to config.skylight.environments, so no data will be sent to skylight.io.
```

I just don't want to be nagged every time I launch a console.

I don't think any of this is mentioned in the docs, and I'm still not quite sure everything that's possible after reading [the code](https://github.com/skylightio/skylight-ruby/blob/2944f1de38681daa73397b84a4c015317624dadf/lib/skylight/config.rb#L376).  Would appreciate some more information.  Thanks!

**Comment by aprescott** [comment]
+1 on this being fairly confusing. For instance, it's not really obvious why setting `alert_log_file` should disable the warning about running in a dev environment.

> HOWEVER it disables all warnings, not just the rails console nag. [...]  I definitely would like to continue to receive these warnings

Again, +1 on wanting to receive problematic warnings in general.

**Comment by sandstrom** [comment]
@wagenet Would it be possible to simply remove this warning. Seems kind of redundant to 'warn' that Skylight isn't reporting anything, because that's totally the expected behaviour in development.

It's kind of like `action_mailer` warning that it won't send outbound emails via an SMTP since it's running in development. Again, it's the expected behaviour so no need to warn about it.

**Comment by carllerche** [comment]
The warning has been helpful to customers in the past who weren't sure why data wasn't being reported. I agree that it isn't an ideal long term solution. We have ideas on how to improve things, but it requires a larger restructuring of how the agent initializes within a rails app. We are currently working on some features and will cycle back afterwards.

**Comment by sandstrom** [comment]
Sounds good, I appreciate that you'll improve it.

**Comment by felixbuenemann** [comment]
I find this warning the opposite of helpful as a brand new user, especially because it isn't mentioned in the [agent docs](https://docs.skylight.io/agent/), so I need to hunt around the sources if it's even a valid option, where to set it and what are valid values…

 Can't you simply give this warning once after running `skylight setup` and remove the nag?

**Comment by sergey-alekseev** [comment]
Just annoying comment about this annoying warning. When do you plan to get rid of this warning or provide clear details on how to disable it?

**Comment by willkoehler** [comment]
I eliminated this warning by putting Skylight in the production group in my Gemfile
```
group :production do
  gem 'skylight'
end
```
Other than needing to run `skylight setup` to configure an app, I'm not sure why Skylight shouldn't just be in the production group?

**Comment by wagenet** [comment]
@willkoehler if you use custom instrumentation you'll also need Skylight in development.

**Comment by wagenet** [comment]
We've got a plan for improving this nag in a future release. For the time being, if you're annoyed by it, set `alert_log_file: /dev/null`.

**Comment by aprescott** [comment]
@wagenet I'm subscribed to this issue so that I can keep track of how to remove the workaround of setting `alert_log_file: /dev/null`. That way I can avoid building up this sort of cruft for various workarounds and temporary fixes in a project. I actually have a commented reference to this GitHub issue in the project's `skylight.yml` file, too.

Since this issue has been closed because of a planned fix, is there an easy way for me to be notified when the fix actually lands? If it'll show as a changelog entry, that's fine too, I'm just wary of issues being closed and getting forgotten, even if they're later fixed.

**Comment by wagenet** [comment]
@aprescott the fix is already merged into our internal branch and a new gem version should be released this week. It will also be reflected in the CHANGELOG.

**Comment by aprescott** [comment]
@wagenet thanks! I'll keep an eye out for it. :+1:

**Comment by kapso** [comment]
@wagenet so whats the fix for this?

I am still seeing this warning anytime I run `rails s` or `rails c`.

**Comment by wagenet** [comment]
@kapso 
It writes a file to `~/.skylight` with `disable_dev_warning: true`

https://github.com/skylightio/skylight-ruby/blob/master/lib/skylight/cli.rb#L67
https://github.com/skylightio/skylight-ruby/blob/master/skylight-core/lib/skylight/core/user_config.rb

**Comment by kapso** [comment]
@wagenet I ran `skylight disable_dev_warning`, but don't see that file generated?

Also, why not have `disable_dev_warning: true` inside `skylight.yml`?

**Comment by wagenet** [comment]
The dev warning is a warning for individual users. It's not really a project-level setting.

**Comment by sandstrom** [comment]
I agree with others, please let us configure this project wide. To most of our team it's just a warning about something they don't know a lot about, so difficult for them to judge if it's an actual problem or not.

***

For now we have the workaround of setting `SKYLIGHT_DISABLE_DEV_WARNING=1` on all developer machines, but I'd rather configure this in the skylight yml config.
