### ISSUE TITLE
Cannot load rails console.

### ISSUE THREAD

**Issue by adamjt** [skylightio/skylight-ruby#2]
Just installed skylight and it is running fine on our staging servers. I added the line 

``` ruby
config.skylight.environments << 'staging'
```

inside "class Application < Rails::Application" in config/application.rb

Here is the output from `bundle exec rails c`

```
[SKYLIGHT] [0.3.1] The Skylight native extension wasn't found. Skylight is not running.
/Users/adam/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/zipruby-0.3.6/lib/zipruby.bundle: warning: already initialized constant Zip::VERSION
/Users/adam/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/rubyzip-0.9.9/lib/zip/constants.rb:2: warning: previous definition of VERSION was here
/Users/adam/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/railties-4.0.3/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `skylight' for #<Rails::Application::Configuration:0x007ff5c6c9a590> (NoMethodError)
```

**Comment by kbullaughey** [comment]
I ran into this issue on 0.10.3, but it was because I was using a library that requires skylight, at which point `Rails` is not defined, so the railtie doesn't load then, but then when it's required for my rails app, skylight has already been required, so again the railtie doesn't load. I fixed this by adding:

    require "skylight/railtie"

In my `config/application.rb` file. 

However, I wonder if there's a more robust way to automatically call the railtie...or maybe I'm instrumenting my other gem wrong....

**Comment by wagenet** [comment]
@kbullaughey I think you may be correct about there being an issue when Skylight is loaded before Rails. I'd like to see if we can fix it. Can you contact us via the in-app messenger or support@skylight.io? We'll be less likely to lose track of the discussion that way.
