### ISSUE TITLE
segfault when recursing inside a sequence when the skylight gem is included

### ISSUE THREAD

**Issue by kevinmook** [skylightio/skylight-ruby#23]
When recursing inside a sequence or n.times (example code included below), ruby will segfault after a few hundred iterations. This is well below the depth I'd expect before a stack overflow.

I've verified this happens in both ruby 2.1.5 and 2.2.0.

ruby_segfault.rb:
```ruby
require "skylight"

module RubySegfault
  extend self
  
  def sequence_loop(counter)
    puts "#{counter}"
    (1 .. 1).each do
      sequence_loop(counter + 1)
    end
  end
  
  def times_loop(counter)
    puts "#{counter}"
    1.times do
      times_loop(counter + 1)
    end
  end
  
  def while_loop(counter)
    puts "#{counter}"
    while true do
      while_loop(counter + 1)
    end
  end
end

case ARGV[0]
  when "sequence" then RubySegfault.sequence_loop(0)
  when "times" then RubySegfault.times_loop(0)
  when "while" then RubySegfault.while_loop(0)
end
```

$ ruby --version
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin13.0]

$ ruby ruby_segfault.rb sequence
0
1
2
...
403
404
Segmentation fault: 11

$ ruby ruby_segfault.rb times
0
1
2
...
419
420
Illegal instruction: 4

Note that this _doesn't_ happen in a while loop and properly raises a SystemStackError:

$ ruby ruby_segfault.rb while
0
1
2
...
9355
9356
/Users/kevin/Desktop/ruby_segfault.rb:21: stack level too deep (SystemStackError)

Finally, if you remove 'require "skylight"' all three methods properly raise a SystemStackError.

**Comment by ericdfields** [comment]
+1

**Comment by carllerche** [comment]
We are currently investigating.

**Comment by carllerche** [comment]
A quick update. We've been able to reproduce the issue and tracked it down to the Rust runtime initialization on the version of Rust that we froze to. Rust 1.0 alpha (which was just released today) has removed the required runtime initialization, so our plan was to update the agent to use the latest Rust.

This is proving to be a bit tricky as some dependencies haven't updated quite yet.

The good news is that we haven't been able to recreate a segv in situations besides a stack overflow, so that is something at least.

I'm hoping that we should be able to move the agent to the latest Rust early next week and then hopefully that will resolve the issue. Otherwise, we will work with the Rust core team to figure out what is going on.

**Comment by kevinmook** [comment]
Great, thanks for the update

**Comment by janraasch** [comment]
Hi guys, what's the status here?

**Comment by carllerche** [comment]
Hey, sorry for the delay. I've actually been working on this for a while. The issue is related to something in the Rust version that we are currently using. Fixing this issue is blocked on getting the agent compiling on the latest Rust which has changed a lot since we locked versions. It's been quite a large task, but I am close to finishing. Hopefully I will be able to report back with a fix soon, but this is turning out to be quite a yak shave.

**Comment by janraasch** [comment]
I can only imagine...

![yak_shave](https://cloud.githubusercontent.com/assets/425211/6797867/71e4a3be-d207-11e4-9890-a20ece7922f3.jpg)

:).

On a more serious note: Thank you for your reply and explaination. Looking forward to hearing back from you once the fix is ready.

**Comment by micahlmartin** [comment]
Any update on this?

**Comment by wagenet** [comment]
The 0.7 beta series is running with the latest Rust nightly. I've run the ruby_segfault.rb successfully on Ruby 2.2.2 with 0.7 beta and I don't get any errors. I'm going to consider this resolved, but please let me know if you have any further issues.
