### ISSUE TITLE
Feature Request: Support Sidekiq

### ISSUE THREAD

**Issue by blatyo** [skylightio/skylight-ruby#26]
I built this gem to add support for Sidekiq for one of my projects. I think it would make a great addition to this gem.

https://github.com/lintci/sidekiq-skylight

**Comment by psugihara** [comment]
This is sweet, thank you.

**Comment by wagenet** [comment]
First-class support for Sidekiq is planned for the future.

**Comment by wagenet** [comment]
I'm closing this ticket for now. If you'd like to get your account marked as wanting Sidekiq support, please email support@skylight.io or click the "?" button in the app UI and send us a message.

**Comment by krainboltgreene** [comment]
It's the future calling, is there first class support?

**Comment by wagenet** [comment]
@krainboltgreene not yet. We care about it, but it doesn't fit into the current model of instrumenting user-facing requests. It's essentially a new product (though with some shared infrastructure) and we haven't yet had the resources to allocate to it. See also https://www.skylight.io/support/faqs#can-i-instrument-background-jobs-like-sidekiq. Believe me, we would _love_ to be able to support Sidekiq and other background jobs. It's a regular point of conversation for us.

**Comment by krainboltgreene** [comment]
That's great to hear @wagenet. For anyone else looking sidekiq-skylight works well for the moment.

**Comment by wagenet** [comment]
@krainboltgreene yeah, that does work for certain cases and if it works in yours, great!

**Comment by jfelchner** [comment]
@wagenet I don't feel that closing this issue with a "won't fix now but maybe someday" is appropriate.  I also feel like this is the perfect place to track interest rather than having everyone email support@skylight.io.  Sidekiq is the most popular queuing library for Ruby.  Not supporting it is a non-starter for many apps who want to use Skylight.

Saying that it's a "new product" doesn't make any sense to me.  You have `resque` support and `sidekiq-skylight` does a decent job with the existing UI.  If you want to break it off into a "new product" later, then cool, but I don't think it's reasonable to say "Well if we put it into Skylight as-is, it isn't going to be perfect, so we're not going to do it at all."

If Skylight was open source alone and you were doing this in your spare time, then it'd be one thing, but it's a paid product (I currently have three paying accounts) and it's been almost three years since this issue was first opened.  Therefore the "we haven't been able to allocate resources" rings a little hollow to me.

Thanks for the work on Skylight!

**Comment by wagenet** [comment]
@jfelchner currently we have 6 engineers on our team, three of which are senior, of which two are largely occupied with consulting. While I agree that three years seems like a long time, we actually don't have much time to rest. We are working on hiring more engineers, but as you're probably aware, good seniors are hard to come by.

Rest assured that we haven't forgotten about Sidekiq support. We know how much you, and many of our other customers, and even we ourselves want first class support for it.

Thanks again for being a paying customer and sorry that we don't yet have something to offer here.
