### ISSUE TITLE
[SKYLIGHT] [0.3.4] The Skylight native extension wasn't found. Skylight is not running.

### ISSUE THREAD

**Issue by jdx** [skylightio/skylight-ruby#5]
```
✗ gem install skylight
Fetching: skylight-0.3.4.gem (100%)
Building native extensions.  This could take a while...
Successfully installed skylight-0.3.4
1 gem installed
✗ skylight
[SKYLIGHT] [0.3.4] The Skylight native extension wasn't found. Skylight is not running.
Commands:
  skylight help [COMMAND]  # Describe available commands or one specific command
  skylight setup           # Sets up a new app
```

**Comment by WojtekKruszewski** [comment]
For anyone who finds this ticket googling for same error message:

OS X is now supported but I'm still getting this error message because native extension silently failed to install. Installing gem with SKYLIGHT_REQUIRED env variable makes installation fail with proper error message:

    $ `SKYLIGHT_REQUIRED=true gem install skylight`
    I, [2015-05-05T12:18:50.699498 #19490]  INFO -- : [SKYLIGHT] attempting to fetch from remote; uri=https://s3.amazonaws.com/skylight-agent-packages/skylight-native/0.5.0-fbaa3ed/skylight_x86_64-darwin.tar.gz

So it's a familiar OpenSSL CA problem not related to Skylight.

**Comment by lazybios** [comment]
@WojtekKruszewski  so how to deal with OpenSSL CA issue?

**Comment by WojtekKruszewski** [comment]
@lazybios Haven't had this problem with OpenSSL in like two years. Last time I remember it was something like `brew install openssl && brew link openssl --force && brew install curl-ca-bundle` and then recompiling Ruby with RVM.
