### ISSUE TITLE
Have you considered an Ruby client without activesupport?

### ISSUE THREAD

**Issue by dentarg** [skylightio/skylight-ruby#87]
activesupport is quite the heavy dependency for non-Rails apps, have you considered making it optional for non-Rails apps? (We use Sinatra)

**Comment by wagenet** [comment]
@dentarg what's your specific concern in regards to "heaviness"?

**Comment by dentarg** [comment]
@wagenet I just used my "gut feeling" for this suggestion. We often build lightweight Sinatra applications, so keeping `Gemfile.lock` short feels nice. I think I took inspiration from https://github.com/thoughtbot/climate_control/pull/18, but your situation might be different.

I've seen that [newrelic_rpm](https://github.com/newrelic/rpm) has no dependencies (but they do vendor some things). Feels like a smart goal for a monitoring gem.

**Comment by wagenet** [comment]
@dentarg while I'm sure ActiveSupport add some overhead we're actually much lighter-weight. All of our heavy processing is done in a compiled native agent in a separate process that is much faster and uses less memory. ActiveSupport has some really nice instrumentation hooks that are also used by other libraries as well. Attempting to completely disconnect from this would hurt our overall metrics. However, if you can provide some concrete information to show that this does have a significant effect on your application, I'd definitely be interested in revisiting this.

**Comment by dentarg** [comment]
@wagenet thanks for explaining, I have no concrete information right now, so I'm fine with closing this as you did. Just curious though, are the ActiveSupport instrumentation hooks used in non-Rails applications?

**Comment by wagenet** [comment]
@dentarg I'm not sure how common they are, but I do know that Grape, for one, uses ActiveSupport instrumentation.

**Comment by scotje** [comment]
I think the most common issue is not the "weight" of ActiveSupport but the fact that you get all the monkey patching to built in classes (https://github.com/rails/rails/tree/master/activesupport/lib/active_support/core_ext) which may conflict or have unanticipated side-effects on mature (non-Rails) codebases that were built without ActiveSupport.

In our case it increases the barrier to adopting Skylight by making the decision "do I want to evaluate Skylight and also introduce all of ActiveSupport's monkey-patches across the entire codebase and make sure that doesn't break anything?" instead of the much simpler "do I want to evaluate Skylight?" Not to say that the answer to the harder question is definitely "no" but the increased time/cost pushes it down the priority list.

My opinion is that ActiveSupport is something that should be opted into at the project level and shouldn't come along as a second-order dependency.

It's a shame the notification/instrumentation parts are not available on their own. I haven't looked at the code but I wonder if an aspirational goal might be to only take advantage of the ActiveSupport::Notification stuff if it's already present and available?

(Sorry to necro this issue.)

**Comment by wagenet** [comment]
@scotje ActiveSupport doesn't automatically require the core extensions. These are something that you can choose to require.

**Comment by scotje** [comment]
@wagenet Right, but have the maintainers decided that the skylight gem isn't going to use any of them in a future release? (Or is there a specific version increment that would induce?)

I guess the point is that when it's a dependency of a dependency, I _don't_ get to "choose" to require them, the maintainer of my dependency does. :(

**Comment by wagenet** [comment]
@scotje it isn't our intent to use the extensions. If you notice that we're causing them to be used anywhere, please let me know.
